# Generated by Django 3.2.7 on 2021-10-02 11:09

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='default/default.png', null=True, upload_to=account.models.user_directory_path),
        ),
    ]
