# Generated by Django 3.2.7 on 2021-10-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_applyauthor_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyauthor',
            name='deactivated',
            field=models.BooleanField(default=False),
        ),
    ]
