# Generated by Django 3.2.7 on 2021-10-02 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_notification_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='application',
        ),
    ]
