# Generated by Django 3.2.7 on 2021-09-16 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('liked_post', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='liked_blog', to='post.post')),
                ('liker_post', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='liker_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
